version: v1
description: Nebula Provision Demo

steps:
- name: init-workflow
  image: alpine:latest
  input:
    - echo "Initializing workflow - Nebula Provision Demo"
    - echo "Provisioning a GKE cluster"
- name: provision-cluster
  image: gcr.io/nebula-tasks/nebula-terraform:bf8ecb9
  spec:
    provider: gcp
    project: docs-pfc
    clusterName: nebula-test
    credentials:
      credentials.json:
        $type: Secret
        name: credentials
    stateStorename: nebula-bucket
    zones: us-west2-b
    region: us-west2  
    git:
      name: nebula-workflow-examples
      repository: https://github.com/hestonhoffman/nebula-workflow-examples.git
  dependsOn:
  - init-workflow
- name: slack-notify
  image: gcr.io/nebula-tasks/nebula-slack-notification:bf8ecb9
  spec:
    apitoken:
      $type: Secret
      name: slack-token
    channel: "#heston-test"
    message: "Sig?"
  dependsOn:
  - provision-cluster
